const skills = {
  "Programming Languages": ["JavaScript", "PHP"],
  Frontend: ["HTML", "CSS", "Bootstrap", "SASS", "ReactJS", "Redux", "jQuery"],
  Backend: ["Node.js", "Express.js"],
  "Version Control": ["Git", "GitHub"],
  Testing: ["Mocha", "Jest"],
  "Soft Skills": [
    "Analytical Thinking",
    "Troubleshooting",
    "Networking",
    "Enthusiasm",
    "Effective Communicator",
    "Team Player",
    "Problem Solving",
  ],
};
const transcript = {
  Codecademy: {
    year: "2022-Present",
    image: "images/education/Codecademy.svg.png",
    certificate: {
      course: "Full-Stack Engineer Career Path",
      link: "https://www.codecademy.com/profiles/koliyus",
      lessons: [
        "Learn Redux",
        "Learn Advanced React",
        "Learn React Router v6",
        "Learn React Router v5",
        "Learn React Testing",
        "Create a Front-End App with React",
        "Learn React",
        "Learn JavaScript Unit Testing",
        "Learn PHP Skill Path",
        "Learn Node.js",
        "Learn Git & GitHub",
        "Learn the Command Line",
        "Learn jQuery",
        "Learn the Basics of Regular Expressions",
        "Building Interactive JavaScript Websites",
        "Learn Intermediate JavaScript",
        "Learn JavaScript",
        "Learn Bootstrap",
        "Learn Sass",
        "Learn Navigation Design",
        "Build a Website with HTML, CSS, and GitHub Pages",
        "Learn Intermediate CSS",
        "Learn CSS",
        "Learn HTML",
        "Learn How to Code",
      ],
    },
  },
  freeCodeCamp: {
    year: "2023-Present",
    image: "images/education/FreeCodeCamp_logo.svg.png",
    certificate: [
      {
        course: "JavaScript Algorithms and Data Structures",
        link: "https://www.freecodecamp.org/certification/koliyus/javascript-algorithms-and-data-structures",
        lessons: [
          "Basic JavaScript",
          "ES6",
          "Regular Expressions",
          "Debugging",
          "Basic Data Structures",
          "Basic Algorithm Scripting",
          "Object Oriented Programming",
          "Intermediate Algorithm Scripting",
          "JavaScript Algorithms and Data Structures Projects",
        ],
      },
      {
        course: "Responsive Web Design",
        link: "https://www.freecodecamp.org/certification/koliyus/responsive-web-design",
        lessons: ["HTML", "CSS"],
      },
    ],
  },
  Udemy: {
    year: "2023-Present",
    image: "images/education/Udemy_logo.svg.png",
    certificate: [
      {
        courseName: "The Ultimate React Course",
        lessons: [
          "React Fundamentals",
          "How to Think About State",
          "How to Think About Components",
          "Deep Dive into Effects and useEffect",
          "Deep Dive into Hooks",
          //        "Performance Optimization",
          //   "Advanced State Management",
          //      "Building Single-Page Applications (SPA)",
          //   "Building Real-World Features",
          //    "Creating Your Own Backend with Supabase",
          //       "How to Style React Apps",
          //      "Advanced React Patterns",
          // "How React Works Behind the Scenes",
          // "Next.js with the 'app' Router",
        ],
      },
      {
        courseName: "The Web Developer Bootcamp",
        lessons: [
          // "Maps and Geocoding",
          // "Image Upload and Storage",
          // "Cloud Databases",
          // "Deploying Apps",
          // "Developer Best Practices",
          // "Common Security Issues - SQL Injection, XSS, etc.",
          // "Authorization",
          // "Cookies & Sessions",
          // "Authentication From Scratch",
          // "Mongoose",
          // "Schema Design",
          // "Database Associations",
          // "MongoDB",
          // "SQL vs. NoSQL databases",
          // "REST",
          // "Templating",
          // "ExpressJS",
          // "NPM",
          // "NodeJS",
          // "SemanticUI",
          "ReactJS",
          "Unix (Command Line) Commands",
          "JavaScript",
          "Asynchronous JavaScript",
          "AJAX and API",
          "DOM Manipulation",
          "Bootstrap 4 and 5",
          "Bulma CSS Framework",
          "HTML",
          "CSS3",
          "Flexbox",
          "Responsive Design",
        ],
      },
    ],
  },
  "ITT Technical Institute": {
    year: "2002-2008",
    image: "images/education/ITTTech.png",
    degrees: [
      {
        degreeName:
          "Associates of Applied Science in Computer Drafting and Design",
        lessons: [
          "Dynamics in an Information Society",
          "Computers in Technology",
          "Problem Solving",
          "Introduction to Design and Drafting",
          "Drafting/CAD Methods",
          "College Mathematics I",
          "Architectural Drafting I",
          "Rapid Visualization",
        ],
      },
      {
        degreeName:
          "Bachelor of Science in Digital Entertainment and Game Design",
        lessons: [
          "Introduction to Computer Programming",
          "Animation I",
          "Audio/Video Techniques",
          "Introduction to Gaming Technology",
          "Managing Game Development",
          "Research Methods",
        ],
      },
    ],
  },
};
