export const resumeData = {
  skills: {
    "Programming Languages": ["JavaScript", "PHP"],
    Frontend: [
      "Redux",
      "ReactJS",
      "jQuery",
      "Bootstrap",
      "SASS",
      "CSS",
      "HTML",
    ],
    Backend: ["Node.js", "Express.js"],
    "Version Control": ["Git", "GitHub"],
    Testing: ["Mocha", "Jest"],
    "Soft Skills": [
      "Analytical Thinking",
      "Troubleshooting",
      "Networking",
      "Enthusiasm",
      "Effective Communicator",
      "Team Player",
      "Problem Solving",
    ],
  },

  experience: [
    {
      company: "Be Original Tours- Berlin Pubcrawl",
      title: "Manager",
      duration: "2019-2022",
      responsibilities: [
        "As a tour leader, responsible for guiding groups of tourists through various locations and providing entertainment of the night life.",
        "Responsible for hiring and training new tour guides, ensuring that they were knowledgeable about the sites and could effectively communicate with tourists.",
        "Was responsible for creating and managing the weekly schedules for both the tour guides and the tour groups, ensuring that everyone was assigned.",
        "Established and negotiated partnerships with venue locations to ensure that the tours had access to the best possible locations and attractions.",
        "Overseeing the payroll process, ensuring that everyone was paid accurately and on time.",
        "Managed meeting point, which included registering customers and processing payments.",
      ],
      imageSrc: "images/experiece/beoriginal(whole).png",
    },
    {
      company: "Erd-maennchen Event und Gastronomieservice GmbH",
      title: "Event Service Assistant",
      duration: "2018-2019",
      responsibilities: [
        "Assisted with the construction and deconstruction of concerts and various events.",
        "Supported delivery and pickup services of furnishings for events.",
        "Maintained accountability of working hours for the crew shift.",
      ],
      imageSrc: "images/experiece/erdmaennchen(whole).png",
    },
    {
      title: "Petroleum Supply Specialist",
      company: "US Army",
      duration: "2009-2016",
      responsibilities: [
        "Liaise with leadership officials to maintain accountability of 70K gallons of diesel fuel.",
        "Coordinated the distribution and accumulation of 10K gallons of diesel fuel allowing multinational organizations to complete a unified operation.",
        "Trained and mentored 200 Afghan military trainees in the fundamentals of driving in hazardous environments.",
        "Gained knowledge of maintenance and usage on various military vehicles.",
        "Obtain knowledge on assembling fuel operation systems.",
      ],
      imageSrc: "images/experiece/usarmy(whole).png",
    },
    {
      title: "Baumholder BOSS President",
      company: "BOSS Program(US Army)",
      duration: "2015-2016",
      responsibilities: [
        "Facilitated fundraising activities generating 80% in profit from sales through hosting community events.",
        "Designed guidelines for personnel from 18 separate sections to follow in order to work more effectively.",
        "Consistently conducted briefs for new personnel inspiring their morale for the area they relocated.",
        "Coordinated events for leisure travel and volunteering of communities.",
        "Build partnerships to construct profit and nonprofit programs.",
        "Conveyed monthly, quarterly, and annual budget and activities.",
        "Instructed employees on and modified the standards required for the organization.",
      ],
      imageSrc: "images/experiece/boss(whole).png",
    },
    {
      title: "CAD Operator",
      company: "Reich Design Associates. P.L.C",
      duration: "2006-2007",
      responsibilities: [
        "Completed and modified detailed architectural plans for residential and commercial projects, ensuring adherence to design specifications and building codes.",
        "Collaborated with lead architect to refine layouts and enhance functionality in interior and exterior designs.",
        "Utilized AutoCAD and other design software to create precise blueprints, improving project visualization and accuracy.",
        "Managed multiple design projects, ensuring timely delivery while maintaining quality and detail in architectural drawings.",
      ],
      imageSrc: "images/experiece/reichdesign(whole).png",
    },
    {
      title: "CAD Operator",
      company: "Tidewater Naval Architects",
      duration: "2004-2005",
      responsibilities: [
        "Created and revised detailed naval architectural designs, including hull structures, interior layouts, and exterior features, following technical specifications.",
        "Assisted in design modifications during the construction process, ensuring clear communication between design and construction teams.",
        "Applied advanced AutoCAD techniques to improve the efficiency and precision of naval design projects.",
      ],
      imageSrc: "images/experiece/tidewater(whole).png",
    },
  ],
  education: {
    Codecademy: {
      year: "2022-Present",
      image: "images/education/Codecademy.svg.png",
      certificate: {
        course: "Full-Stack Engineer Career Path",
        link: "https://www.codecademy.com/profiles/koliyus",
        lessons: [
          "Learn Redux",
          "Learn Advanced React",
          "Learn React Router v6",
          "Learn React Router v5",
          "Learn React Testing",
          "Create a Front-End App with React",
          "Learn React",
          "Learn JavaScript Unit Testing",
          "Learn PHP Skill Path",
          "Learn Node.js",
          "Learn Git & GitHub",
          "Learn the Command Line",
          "Learn jQuery",
          "Learn the Basics of Regular Expressions",
          "Building Interactive JavaScript Websites",
          "Learn Intermediate JavaScript",
          "Learn JavaScript",
          "Learn Bootstrap",
          "Learn Sass",
          "Learn Navigation Design",
          "Build a Website with HTML, CSS, and GitHub Pages",
          "Learn Intermediate CSS",
          "Learn CSS",
          "Learn HTML",
          "Learn How to Code",
        ],
      },
    },
    freeCodeCamp: {
      year: "2023-Present",
      image: "images/education/FreeCodeCamp_logo.svg.png",
      certificate: [
        {
          course: "JavaScript Algorithms and Data Structures",
          link: "https://www.freecodecamp.org/certification/koliyus/javascript-algorithms-and-data-structures",
          lessons: [
            "Basic JavaScript",
            "ES6",
            "Regular Expressions",
            "Debugging",
            "Basic Data Structures",
            "Basic Algorithm Scripting",
            "Object Oriented Programming",
            "Intermediate Algorithm Scripting",
            "JavaScript Algorithms and Data Structures Projects",
          ],
        },
        {
          course: "Responsive Web Design",
          link: "https://www.freecodecamp.org/certification/koliyus/responsive-web-design",
          lessons: ["HTML", "CSS"],
        },
      ],
    },
    Udemy: {
      year: "2021-Present",
      image: "images/education/Udemy_logo.svg.png",
      certificate: [
        {
          course: "The Ultimate React Course",
          lessons: [
            "React Fundamentals",
            "How to Think About State",
            "How to Think About Components",
            "Deep Dive into Effects and useEffect",
            "Deep Dive into Hooks",
            //        "Performance Optimization",
            //   "Advanced State Management",
            //      "Building Single-Page Applications (SPA)",
            //   "Building Real-World Features",
            //    "Creating Your Own Backend with Supabase",
            //       "How to Style React Apps",
            //      "Advanced React Patterns",
            // "How React Works Behind the Scenes",
            // "Next.js with the 'app' Router",
          ],
        },
        {
          course: "The Web Developer Bootcamp",
          lessons: [
            // "Maps and Geocoding",
            // "Image Upload and Storage",
            // "Cloud Databases",
            // "Deploying Apps",
            // "Developer Best Practices",
            // "Common Security Issues - SQL Injection, XSS, etc.",
            // "Authorization",
            // "Cookies & Sessions",
            // "Authentication From Scratch",
            // "Mongoose",
            // "Schema Design",
            // "Database Associations",
            // "MongoDB",
            // "SQL vs. NoSQL databases",
            // "REST",
            // "Templating",
            // "ExpressJS",
            // "NPM",
            // "NodeJS",
            // "SemanticUI",
            "ReactJS",
            "Unix (Command Line) Commands",
            "JavaScript",
            "Asynchronous JavaScript",
            "AJAX and API",
            "DOM Manipulation",
            "Bootstrap 4 and 5",
            "Bulma CSS Framework",
            "HTML",
            "CSS3",
            "Flexbox",
            "Responsive Design",
          ],
        },
      ],
    },
    "ITT Technical Institute": {
      year: "2002-2008",
      image: "images/education/ITTTech.png",
      degrees: [
        {
          degreeName:
            "Associates Degree of Applied Science in Computer Drafting and Design",
          lessons: [
            "Dynamics in an Information Society",
            "Computers in Technology",
            "Problem Solving",
            "Introduction to Design and Drafting",
            "Drafting/CAD Methods",
            "College Mathematics I",
            "Architectural Drafting I",
            "Rapid Visualization",
          ],
        },
        {
          degreeName:
            "Bachelor Degree of Science in Digital Entertainment and Game Design",
          lessons: [
            "Introduction to Computer Programming",
            "Animation I",
            "Audio/Video Techniques",
            "Introduction to Gaming Technology",
            "Managing Game Development",
            "Research Methods",
          ],
        },
      ],
    },
  },
};
